Fix for database disconnections When compiling this project for use on OC be sure to include the .classpath in the plugin jar. Excluding it will cause java.lang.NoClassDefFoundError exceptions.